// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCScHbZwGWSJMAKfMt8oS56lft3fghUM3U',
    appId: '1:336149199830:web:ee8b77d66d837db786c277',
    messagingSenderId: '336149199830',
    projectId: 'fir-test-b82b8',
    authDomain: 'fir-test-b82b8.firebaseapp.com',
    storageBucket: 'fir-test-b82b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaOtlUo-bC9vJE52BAMuzvWtvM_on6TKU',
    appId: '1:336149199830:android:91abfa67633d98c286c277',
    messagingSenderId: '336149199830',
    projectId: 'fir-test-b82b8',
    storageBucket: 'fir-test-b82b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARtMVu_NVZb3D4kmoNKw1_oJzcPsze0CQ',
    appId: '1:336149199830:ios:c026c741ee5416fc86c277',
    messagingSenderId: '336149199830',
    projectId: 'fir-test-b82b8',
    storageBucket: 'fir-test-b82b8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARtMVu_NVZb3D4kmoNKw1_oJzcPsze0CQ',
    appId: '1:336149199830:ios:c026c741ee5416fc86c277',
    messagingSenderId: '336149199830',
    projectId: 'fir-test-b82b8',
    storageBucket: 'fir-test-b82b8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCScHbZwGWSJMAKfMt8oS56lft3fghUM3U',
    appId: '1:336149199830:web:3d1ba0f4b8af659186c277',
    messagingSenderId: '336149199830',
    projectId: 'fir-test-b82b8',
    authDomain: 'fir-test-b82b8.firebaseapp.com',
    storageBucket: 'fir-test-b82b8.firebasestorage.app',
  );
}
